<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\A2D.AlertMigrator.Application\A2D.AlertMigrator.Application.csproj" />
    <ProjectReference Include="..\A2D.AlertMigrator.Domain\A2D.AlertMigrator.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
  </ItemGroup>
</Project>
